import type { Character } from '../types'

// API base URL - defaults to same origin in production
const API_BASE_URL = import.meta.env.VITE_API_URL || ''

// Character summary returned by list endpoint
export interface CharacterSummary {
  id: string
  name: string
  class: string
  level: number
  species: string
  updated_at: string
}

// Error class for API-related errors
export class ApiError extends Error {
  constructor(
    message: string,
    public status: number
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

// Helper function to handle fetch responses
async function handleResponse<T>(response: Response): Promise<T> {
  if (!response.ok) {
    let message = `Request failed with status ${response.status}`
    try {
      const errorData = await response.json()
      if (errorData.error) {
        message = errorData.error
      }
    } catch {
      // Use default message if response isn't JSON
    }
    throw new ApiError(message, response.status)
  }
  return response.json()
}

/**
 * Create a new character
 * @param data - Character data (without id, which will be generated by the server)
 * @returns The created character with its generated id
 */
export async function createCharacter(
  data: Omit<Character, 'id'>
): Promise<Character> {
  const response = await fetch(`${API_BASE_URL}/api/characters`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(data),
  })
  return handleResponse<Character>(response)
}

/**
 * Get a character by ID
 * @param id - The character's unique ID
 * @returns The character data
 * @throws ApiError if character not found (404) or other error
 */
export async function getCharacter(id: string): Promise<Character> {
  const response = await fetch(`${API_BASE_URL}/api/characters/${id}`)
  return handleResponse<Character>(response)
}

/**
 * Update an existing character
 * @param id - The character's unique ID
 * @param data - Updated character data
 * @returns The updated character
 * @throws ApiError if character not found (404) or other error
 */
export async function updateCharacter(
  id: string,
  data: Omit<Character, 'id'>
): Promise<Character> {
  const response = await fetch(`${API_BASE_URL}/api/characters/${id}`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(data),
  })
  return handleResponse<Character>(response)
}

/**
 * Delete a character by ID
 * @param id - The character's unique ID
 * @returns Success confirmation
 * @throws ApiError if character not found (404) or other error
 */
export async function deleteCharacter(
  id: string
): Promise<{ success: boolean }> {
  const response = await fetch(`${API_BASE_URL}/api/characters/${id}`, {
    method: 'DELETE',
  })
  return handleResponse<{ success: boolean }>(response)
}

/**
 * List all characters
 * @returns Array of character summaries sorted by updated_at (most recent first)
 */
export async function listCharacters(): Promise<CharacterSummary[]> {
  const response = await fetch(`${API_BASE_URL}/api/characters`)
  return handleResponse<CharacterSummary[]>(response)
}
